
# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
      - christian.guba@dart-racing.de
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu 
    - WRITABLE_SOURCE=true
    - CATKIN_CONFIG='--isolated-devel'
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic"  PRERELEASE=false
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  
script:
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 

