# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from piksi_ros/Obs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import piksi_ros.msg

class Obs(genpy.Message):
  _md5sum = "c4d3fae07ec1003bc792498ae2d73eb8"
  _type = "piksi_ros/Obs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 P # Psueudorange observation [cm]
piksi_ros/CarrierPhase L # Carrier phase [cycles]
uint8 cn0 # Carrier-to-Noise density [dB Hz * 4]
uint16 lock # Lock indicator. This value changes whenever a satellite signal has lost and regained lock, indicating that the carrier phase ambiguity may have changed
piksi_ros/Sid sid # Satellite identifier

================================================================================
MSG: piksi_ros/CarrierPhase
# Carrier phase observation here is represented as a 40-bit fixed
# point number with Q32.8 layout (i.e. 32-bits of whole cycles and 8-bits of fractional cycles).

int32 i # Carrier phase whole cycles [cycles]
uint8 f # Carrier phase fractional part [cycles/256]

================================================================================
MSG: piksi_ros/Sid
uint16 sat # Constellation-specific satellite identifier
uint8 band # Signal band
uint8 constellation # Constellation to which the satellite belongs
"""
  __slots__ = ['P','L','cn0','lock','sid']
  _slot_types = ['uint32','piksi_ros/CarrierPhase','uint8','uint16','piksi_ros/Sid']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       P,L,cn0,lock,sid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Obs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.P is None:
        self.P = 0
      if self.L is None:
        self.L = piksi_ros.msg.CarrierPhase()
      if self.cn0 is None:
        self.cn0 = 0
      if self.lock is None:
        self.lock = 0
      if self.sid is None:
        self.sid = piksi_ros.msg.Sid()
    else:
      self.P = 0
      self.L = piksi_ros.msg.CarrierPhase()
      self.cn0 = 0
      self.lock = 0
      self.sid = piksi_ros.msg.Sid()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Ii2B2H2B().pack(_x.P, _x.L.i, _x.L.f, _x.cn0, _x.lock, _x.sid.sat, _x.sid.band, _x.sid.constellation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.L is None:
        self.L = piksi_ros.msg.CarrierPhase()
      if self.sid is None:
        self.sid = piksi_ros.msg.Sid()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.P, _x.L.i, _x.L.f, _x.cn0, _x.lock, _x.sid.sat, _x.sid.band, _x.sid.constellation,) = _get_struct_Ii2B2H2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Ii2B2H2B().pack(_x.P, _x.L.i, _x.L.f, _x.cn0, _x.lock, _x.sid.sat, _x.sid.band, _x.sid.constellation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.L is None:
        self.L = piksi_ros.msg.CarrierPhase()
      if self.sid is None:
        self.sid = piksi_ros.msg.Sid()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.P, _x.L.i, _x.L.f, _x.cn0, _x.lock, _x.sid.sat, _x.sid.band, _x.sid.constellation,) = _get_struct_Ii2B2H2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Ii2B2H2B = None
def _get_struct_Ii2B2H2B():
    global _struct_Ii2B2H2B
    if _struct_Ii2B2H2B is None:
        _struct_Ii2B2H2B = struct.Struct("<Ii2B2H2B")
    return _struct_Ii2B2H2B
