yolo_model:

  config_file:
    name: yolo-fsd-tiny.cfg
  weight_file:
    name: yolo-fsd-tiny_3000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Blue Cone
      - Yellow Cone