// Generated by gencpp from file piksi_ros/CarrierPhase.msg
// DO NOT EDIT!


#ifndef PIKSI_ROS_MESSAGE_CARRIERPHASE_H
#define PIKSI_ROS_MESSAGE_CARRIERPHASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piksi_ros
{
template <class ContainerAllocator>
struct CarrierPhase_
{
  typedef CarrierPhase_<ContainerAllocator> Type;

  CarrierPhase_()
    : i(0)
    , f(0)  {
    }
  CarrierPhase_(const ContainerAllocator& _alloc)
    : i(0)
    , f(0)  {
  (void)_alloc;
    }



   typedef int32_t _i_type;
  _i_type i;

   typedef uint8_t _f_type;
  _f_type f;




  typedef boost::shared_ptr< ::piksi_ros::CarrierPhase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_ros::CarrierPhase_<ContainerAllocator> const> ConstPtr;

}; // struct CarrierPhase_

typedef ::piksi_ros::CarrierPhase_<std::allocator<void> > CarrierPhase;

typedef boost::shared_ptr< ::piksi_ros::CarrierPhase > CarrierPhasePtr;
typedef boost::shared_ptr< ::piksi_ros::CarrierPhase const> CarrierPhaseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_ros::CarrierPhase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_ros::CarrierPhase_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_ros': ['/home/christian/DARTFSD/catkin_ws/src/piksi_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_ros::CarrierPhase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_ros::CarrierPhase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_ros::CarrierPhase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03e7515b70723eadfe3c0e1e43e29e21";
  }

  static const char* value(const ::piksi_ros::CarrierPhase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03e7515b70723eadULL;
  static const uint64_t static_value2 = 0xfe3c0e1e43e29e21ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_ros/CarrierPhase";
  }

  static const char* value(const ::piksi_ros::CarrierPhase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Carrier phase observation here is represented as a 40-bit fixed\n\
# point number with Q32.8 layout (i.e. 32-bits of whole cycles and 8-bits of fractional cycles).\n\
\n\
int32 i # Carrier phase whole cycles [cycles]\n\
uint8 f # Carrier phase fractional part [cycles/256]\n\
";
  }

  static const char* value(const ::piksi_ros::CarrierPhase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i);
      stream.next(m.f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarrierPhase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_ros::CarrierPhase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_ros::CarrierPhase_<ContainerAllocator>& v)
  {
    s << indent << "i: ";
    Printer<int32_t>::stream(s, indent + "  ", v.i);
    s << indent << "f: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_ROS_MESSAGE_CARRIERPHASE_H
