// Generated by gencpp from file piksi_ros/SignalStatus.msg
// DO NOT EDIT!


#ifndef PIKSI_ROS_MESSAGE_SIGNALSTATUS_H
#define PIKSI_ROS_MESSAGE_SIGNALSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_ros
{
template <class ContainerAllocator>
struct SignalStatus_
{
  typedef SignalStatus_<ContainerAllocator> Type;

  SignalStatus_()
    : header()
    , num_sats(0)
    , mean_cn0(0.0)
    , median_cn0(0.0)
    , robust_mean_cn0(0.0)  {
    }
  SignalStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_sats(0)
    , mean_cn0(0.0)
    , median_cn0(0.0)
    , robust_mean_cn0(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_sats_type;
  _num_sats_type num_sats;

   typedef float _mean_cn0_type;
  _mean_cn0_type mean_cn0;

   typedef float _median_cn0_type;
  _median_cn0_type median_cn0;

   typedef float _robust_mean_cn0_type;
  _robust_mean_cn0_type robust_mean_cn0;




  typedef boost::shared_ptr< ::piksi_ros::SignalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_ros::SignalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SignalStatus_

typedef ::piksi_ros::SignalStatus_<std::allocator<void> > SignalStatus;

typedef boost::shared_ptr< ::piksi_ros::SignalStatus > SignalStatusPtr;
typedef boost::shared_ptr< ::piksi_ros::SignalStatus const> SignalStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_ros::SignalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_ros::SignalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_ros': ['/home/christian/DARTFSD/catkin_ws/src/piksi_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_ros::SignalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_ros::SignalStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_ros::SignalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_ros::SignalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_ros::SignalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_ros::SignalStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_ros::SignalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e5693267b8a40f28e0cb8ae142b2ffb";
  }

  static const char* value(const ::piksi_ros::SignalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e5693267b8a40f2ULL;
  static const uint64_t static_value2 = 0x8e0cb8ae142b2ffbULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_ros::SignalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_ros/SignalStatus";
  }

  static const char* value(const ::piksi_ros::SignalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_ros::SignalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header # ROS header\n\
\n\
int32 num_sats\n\
\n\
float32 mean_cn0\n\
float32 median_cn0\n\
float32 robust_mean_cn0\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_ros::SignalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_ros::SignalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_sats);
      stream.next(m.mean_cn0);
      stream.next(m.median_cn0);
      stream.next(m.robust_mean_cn0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SignalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_ros::SignalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_ros::SignalStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_sats: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sats);
    s << indent << "mean_cn0: ";
    Printer<float>::stream(s, indent + "  ", v.mean_cn0);
    s << indent << "median_cn0: ";
    Printer<float>::stream(s, indent + "  ", v.median_cn0);
    s << indent << "robust_mean_cn0: ";
    Printer<float>::stream(s, indent + "  ", v.robust_mean_cn0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_ROS_MESSAGE_SIGNALSTATUS_H
